### ISSUE TITLE
百度音乐抓包抓不到了

### ISSUE THREAD

**Issue by wangchengyan** [agxxxx/AIDLMusicPlayer#1]
java.lang.NullPointerException: Attempt to read from field 'java.util.List com.aidlmusicplayer.www.bean.SongBillListBean.song_list' on a null object reference
                                                                           at com.aidlmusicplayer.www.MainActivity$1.onSuccess(MainActivity.java:71)
                                                                           at com.aidlmusicplayer.www.MainActivity$1.onSuccess(MainActivity.java:68)
                                                                           at com.aidlmusicplayer.www.net.NetCallBack.onResponse(NetCallBack.java:33)
                                                                           at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                           at android.os.Handler.handleCallback(Handler.java:761)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:156)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by caishuwei** [comment]
嗯，拿不到数据，返回空对象了
